trigger:
- master

stages:
- stage: Build_packages
  displayName: Build packages
  jobs:
  - job: Debian
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-debian:latest
    steps:
    - script: make
      displayName: Build
    - script: make test
      displayName: Test  
    - script: make package
      displayName: Package  

  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-ubuntu:latest
    steps:
    - script: make
      displayName: Build
    - script: make test
      displayName: Test  
    - script: make package
      displayName: Package  
