#
#
#
# Azure DevOps agent's workspace directory:
#
#   $(Pipeline.Workspace)
#
# Directories inside the agent's workspace:
#
#   $(Build.SourcesDirectory)             - checkout directory
#   $(Build.ArtifactStagingDirectory)     - artifacts staging directory (cleaned automatically before a build)
#   $(Build.BinariesDirectory)            - build directory (not cleaned, unless explicitly requested)
#   $(Common.TestResultsDirectory)        - test results directory
#
# Build.BinariesDirectory contains not only compiled binaries, but also all
# intermediate object files, so if the job happens to run on the same agent,
# it will build incrementally, unless the build directory is explicitly
# cleaned like this:
#
#   - job: X
#     workspace:
#       clean: outputs
#
variables:
  BLDDIR: '$(Build.BinariesDirectory)'

  TEST_RSLT_DIR: $(Common.TestResultsDirectory)

  TEST_RSLT_FILE_WIN: webalizer_windows_test.xml
  TEST_RSLT_FILE_DEB: webalizer_debian_test.xml
  TEST_RSLT_FILE_UBU: webalizer_ubuntu_test.xml
  TEST_RSLT_FILE_FED: webalizer_fedora_test.xml

stages:
- stage: Build_packages
  displayName: Build packages
  jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'src/webalizer.sln'
        feedsToUse: 'select'
        vstsFeed: 'https://api.nuget.org/v3/index.json'
    - task: MSBuild@1
      displayName: Build
      inputs:
        solution: 'src\webalizer.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=..\build\x64\'

    - task: MSBuild@1
      displayName: Build Test
      inputs:
        solution: 'src\test\test.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=..\..\build\test\x64\'
        
    - script: |
        $(Build.SourcesDirectory)\build\test\x64\test.exe --gtest_output=xml:$(TEST_RSLT_DIR)/$(TEST_RSLT_FILE_WIN)
      displayName: Run Test
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE_WIN)'
        searchFolder: '$(TEST_RSLT_DIR)'

    - task: MSBuild@1
      displayName: Package
      inputs:
        solution: 'src\package.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=..\build\x64\'

    #
    # Debian
    #
  - job: Debian
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-debian:latest
    steps:
    - script: |
        make BLDDIR=$(BLDDIR)
      displayName: Build

    - script: |
        make BLDDIR=$(BLDDIR) TEST_RSLT_DIR=$(TEST_RSLT_DIR) TEST_RSLT_FILE=$(TEST_RSLT_FILE_DEB) test
      displayName: Test  
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE_DEB)'
        searchFolder: '$(TEST_RSLT_DIR)'

    - script: |
        make BLDDIR=$(BLDDIR) PKG_OS_ABBR=deb PKG_ARCH_ABBR=x64 package
      displayName: Package
    - publish: '$(BLDDIR)/webalizer-deb-x64-*.tar.gz'
      artifact: Debian package

    #
    # Ubuntu
    #
  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-ubuntu:latest
    steps:
    - script: |
        make BLDDIR=$(BLDDIR)
      displayName: Build

    - script: |
        make BLDDIR=$(BLDDIR) TEST_RSLT_DIR=$(TEST_RSLT_DIR) TEST_RSLT_FILE=$(TEST_RSLT_FILE_UBU) test
      displayName: Test  
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE_UBU)'
        searchFolder: '$(TEST_RSLT_DIR)'

    - script: |
        make BLDDIR=$(BLDDIR) PKG_OS_ABBR=ubu PKG_ARCH_ABBR=x64 package
      displayName: Package
    - publish: '$(BLDDIR)/webalizer-ubu-x64-*.tar.gz'
      artifact: Ubuntu package

    #
    # Fedora
    #
  - job: Fedora
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-fedora:latest
    steps:
    - script: |
        make BLDDIR=$(BLDDIR)
      displayName: Build

    - script: |
        make BLDDIR=$(BLDDIR) TEST_RSLT_DIR=$(TEST_RSLT_DIR) TEST_RSLT_FILE=$(TEST_RSLT_FILE_FED) test
      displayName: Test  
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE_FED)'
        searchFolder: '$(TEST_RSLT_DIR)'

    - script: |
        make BLDDIR=$(BLDDIR) PKG_OS_ABBR=fed PKG_ARCH_ABBR=x64 package
      displayName: Package
    - publish: '$(BLDDIR)/webalizer-fed-x64-*.tar.gz'
      artifact: Fedora package
