trigger:
- master

stages:
- stage: Build_packages
  displayName: Build packages
  jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'src/webalizer.sln'
        feedsToUse: 'select'
        vstsFeed: 'https://api.nuget.org/v3/index.json'
    - task: MSBuild@1
      displayName: Build
      inputs:
        solution: 'src\webalizer.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=..\build\x64\'
    - task: MSBuild@1
      displayName: Build Test
      inputs:
        solution: 'src\test\test.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=..\build\test\x64\'
    - script: '..\build\test\x64\test.exe'
      displayName: Run Test
    - task: MSBuild@1
      displayName: Package
      inputs:
        solution: 'src\package.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=..\build\x64\'
  - job: Debian
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-debian:latest
    steps:
    - script: make
      displayName: Build
    - script: make test
      displayName: Test  
    - script: make package
      displayName: Package  

  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-ubuntu:latest
    steps:
    - script: make
      displayName: Build
    - script: make test
      displayName: Test  
    - script: make package
      displayName: Package  
