trigger:
- master

stages:
- stage: Build_packages
  displayName: Build packages
  jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
    - task: MSBuild@1
      inputs:
        solution: 'src\package.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=..\build\x64\'
        restoreNugetPackages: true
  - job: Debian
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-debian:latest
    steps:
    - script: make
      displayName: Build
    - script: make test
      displayName: Test  
    - script: make package
      displayName: Package  

  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-ubuntu:latest
    steps:
    - script: make
      displayName: Build
    - script: make test
      displayName: Test  
    - script: make package
      displayName: Package  
