variables:
  #
  # Intended upcoming app version on this branch. Once a dot-zero version
  # is released, this version should be updated towards the next release.
  #
  # For example, after 6.1.0 is released and a v6-1 branch is created,
  # pipeline YAML on that branch should be changed to use version 6-1-1
  # for bug fixes and version on master should be changed to 6-2-0 or
  # 7-0-0, whichever is planned. Once 6.1.1 is released, pipeline YAML
  # on branch v6-1 should be changed to use version 6-1-2, and so on.
  #
  VERSION: 6-1-0
  BUILD_NUMBER: $[counter(variables.VERSION, 1)]
  
  # without `format` pipeline run label is reported as unevaluated variable names
  VERSION_LABEL: $[format('{0}-{1}', variables.VERSION, variables.BUILD_NUMBER)]

  #
  # All directories are within Azure DevOps agent's workspace directory:
  #
  #   $(Pipeline.Workspace)
  #

  # source checkout directory
  SRC_DIR: $(Build.SourcesDirectory)

  #
  # Output directory for compiled binaries and intermediate object files.
  #
  # Build.BinariesDirectory is not cleaned before a build, unless explicitly
  # requested. For self-hosted agents this could be used to build incrementally,
  # but for MS-hosted agents chances of this are slim. Nevertheless, scripts in
  # this pipeline should treat this directory as if it may contain files from
  # previous builds, unless it is explicitly cleaned like this:
  #
  #   - job: X
  #     workspace:
  #       clean: outputs
  #
  BUILD_DIR: $(Build.BinariesDirectory)

  # artifacts staging directory (cleaned automatically before a build)
  ARTIFACT_DIR: $(Build.ArtifactStagingDirectory)

  # test results directory
  TEST_RSLT_DIR: $(Common.TestResultsDirectory)

  # a directory for temporary files (cleaned automatically after each job)
  TMP_DIR: $(Agent.TempDirectory)

#
# Pipeline run label (used only for display purposes in this pipeline)
#
name: $(VERSION_LABEL)

stages:
- stage: Build_packages
  displayName: Build packages
  jobs:
  - job: Windows
    variables:
      TEST_RSLT_FILE: webalizer_win_test.xml
  
    pool:
      vmImage: windows-2019

    steps:
    - task: NuGetCommand@2
      displayName: Restore Nuget Packages
      inputs:
        command: 'restore'
        restoreSolution: 'src/webalizer.sln'
        feedsToUse: 'select'
        vstsFeed: 'https://api.nuget.org/v3/index.json'

    - task: MSBuild@1
      displayName: Build
      inputs:
        solution: 'src\webalizer.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=$(BUILD_DIR)\;AZP_BUILD_NUMBER=$(BUILD_NUMBER)'

    - task: MSBuild@1
      displayName: Build Test
      inputs:
        solution: 'src\test\test.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=$(BUILD_DIR)\'
        
    - script: |
        $(BUILD_DIR)\test.exe --gtest_output=xml:$(TEST_RSLT_DIR)/$(TEST_RSLT_FILE)
      displayName: Run Test
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE)'
        searchFolder: '$(TEST_RSLT_DIR)'

      # create output directory for the package
    - script: |
        mkdir $(BUILD_DIR)\x64\$(VERSION_LABEL)
      displayName: Create Package Directories

    - task: MSBuild@1
      displayName: Collect Package Files
      inputs:
        solution: 'src\package.vcxproj'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
        msbuildArguments: '/property:OutDir=$(BUILD_DIR)\x64\$(VERSION_LABEL)\'

    - task: ArchiveFiles@2
      displayName: Make Package
      inputs:
        rootFolderOrFile: '$(BUILD_DIR)\x64\$(VERSION_LABEL)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(ARTIFACT_DIR)/webalizer-win-x64-$(VERSION_LABEL).zip'
        replaceExistingArchive: true

    - publish: '$(ARTIFACT_DIR)/webalizer-win-x64-$(VERSION_LABEL).zip'
      artifact: Windows package

    #
    # Debian
    #
  - job: Debian
    variables:
      TEST_RSLT_FILE: webalizer_deb_test.xml

    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-debian:latest

    steps:
    - script: |
        make clean-deps
      displayName: Clean dependencies

    - script: |
        make BLDDIR=$(BUILD_DIR) AZP_BUILD_NUMBER=$(BUILD_NUMBER)
      displayName: Build

    - script: |
        make BLDDIR=$(BUILD_DIR) TEST_RSLT_DIR=$(TEST_RSLT_DIR) TEST_RSLT_FILE=$(TEST_RSLT_FILE) test
      displayName: Test  
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE)'
        searchFolder: '$(TEST_RSLT_DIR)'

    - script: |
        make BLDDIR=$(BUILD_DIR) PKG_DIR=$(ARTIFACT_DIR) PKG_OS_ABBR=deb PKG_ARCH_ABBR=x64 package
      displayName: Package
    - publish: '$(ARTIFACT_DIR)/webalizer-deb-x64-$(VERSION_LABEL).tar.gz'
      artifact: Debian package

    #
    # Ubuntu
    #
  - job: Ubuntu
    variables:
      TEST_RSLT_FILE: webalizer_ubu_test.xml

    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-ubuntu:latest

    steps:
    - script: |
        make clean-deps
      displayName: Clean dependencies

    - script: |
        make BLDDIR=$(BUILD_DIR) AZP_BUILD_NUMBER=$(BUILD_NUMBER)
      displayName: Build

    - script: |
        make BLDDIR=$(BUILD_DIR) TEST_RSLT_DIR=$(TEST_RSLT_DIR) TEST_RSLT_FILE=$(TEST_RSLT_FILE) test
      displayName: Test  
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE)'
        searchFolder: '$(TEST_RSLT_DIR)'

    - script: |
        make BLDDIR=$(BUILD_DIR) PKG_DIR=$(ARTIFACT_DIR) PKG_OS_ABBR=ubu PKG_ARCH_ABBR=x64 package
      displayName: Package
    - publish: '$(ARTIFACT_DIR)/webalizer-ubu-x64-$(VERSION_LABEL).tar.gz'
      artifact: Ubuntu package

    #
    # Fedora
    #
  - job: Fedora
    variables:
      TEST_RSLT_FILE: webalizer_fed_test.xml

    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-fedora:latest

    steps:
    - script: |
        make clean-deps
      displayName: Clean dependencies

    - script: |
        make BLDDIR=$(BUILD_DIR) AZP_BUILD_NUMBER=$(BUILD_NUMBER)
      displayName: Build

    - script: |
        make BLDDIR=$(BUILD_DIR) TEST_RSLT_DIR=$(TEST_RSLT_DIR) TEST_RSLT_FILE=$(TEST_RSLT_FILE) test
      displayName: Test  
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: '$(TEST_RSLT_FILE)'
        searchFolder: '$(TEST_RSLT_DIR)'

    - script: |
        make BLDDIR=$(BUILD_DIR) PKG_DIR=$(ARTIFACT_DIR) PKG_OS_ABBR=fed PKG_ARCH_ABBR=x64 package
      displayName: Package
    - publish: '$(ARTIFACT_DIR)/webalizer-fed-x64-$(VERSION_LABEL).tar.gz'
      artifact: Fedora package

    #
    # Doxygen docs
    #
  - job: Doxygen
    pool:
      vmImage: ubuntu-latest
    container: stonesteps/webalizer-fedora-doxygen:latest

    # make sure there are no stale files in the build directory
    workspace:
      clean: outputs

    steps:
    - script: >
        DOXYGEN_BRANCH=$(Build.SourceBranchName)
        DOXYGEN_INPUT=$(SRC_DIR)/src
        DOXYGEN_OUTPUT=$(BUILD_DIR)/webalizer-doxygen
        doxygen $(SRC_DIR)/devops/doxygen.conf
      displayName: Generate Doxygen docs

    - task: ArchiveFiles@2
      displayName: Package Doxygen docs
      inputs:
        rootFolderOrFile: '$(BUILD_DIR)/webalizer-doxygen'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(ARTIFACT_DIR)/webalizer-doxygen-$(VERSION_LABEL).tar.gz'
        replaceExistingArchive: true

    - publish: '$(ARTIFACT_DIR)/webalizer-doxygen-$(VERSION_LABEL).zip'
      artifact: Doxygen docs
