# Debian 9.4 (based on stretch-slim) image with all dependencies installed
image: stonesteps/webalizer:debian-stretch

pipelines:
  default:
    - step:
        name: Build
        script: 
          - make
          - make test
